# Week 2 exercises: NumPy, Pandas, and Modules

*Complete all exercises in this notebook during week 2. The exercises are not submitted — this is purely for your own learning and for preparing for the assignments, project and exam.*

Note! You should always complete the tasks first without using AI. If you need AI to get through these tasks, then you will not be able to pass the oral exam. AI can be used to check if your code could be simplified or improved after you solve the task.

---

## Part 1: Modules, Packages and Libraries

### Exercise 1: Importing Modules

a) Import the `math` module and use it to compute the square root of 144 and the value of e^2. Print both results.

b) Import only the `ceil` and `floor` functions from the `math` module. Apply both to the value `7.3` and print the results.

c) Import the `random` module with the alias `rng`. Use `rng.randint(1, 100)` to generate and print a random integer between 1 and 100.

In [16]:
import math as math

square_144 = math.sqrt(144)
exp_e2 = math.exp(2)

print(square_144)
print(exp_e2)

12.0
7.38905609893065


In [ ]:
#b)
from math import ceil, floor

ceiling_x = math.ceil(7.3)
floor_x = math.floor(7.3)

print(ceiling_x)
print(floor_x)

In [18]:
#c)
import random as rng

print(rng.randint(1, 100))

48


### Exercise 2: Exploring the Standard Library

a) Import the `datetime` module. Create a variable `today` that stores today's date using `datetime.date.today()`. Print the result.

b) Import the `os` module and use `os.getcwd()` to print your current working directory.

In [21]:
# YOUR CODE HERE

#a)
import datetime as dt

today = dt.date.today()

print(today)

2026-03-25


In [22]:
#b)
import os as os

working_directory = os.getcwd()

print(working_directory)

C:\Users\a\!Uni Exercises


## Part 2: NumPy

### Exercise 3: Creating and Inspecting Arrays

a) Import NumPy as `np`. Create a 1D array called `revenues` containing the values: `[120, 95, 200, 180, 160, 210, 190]`. These represent daily revenues in thousands of euros for a week.

b) Print the array's `ndim`, `shape`, `size`, and `dtype`.

c) Create a 2D array with shape `(3, 4)` containing integers from 1 to 12 using `np.arange()` and `.reshape()`. Print the array.

In [26]:
# YOUR CODE HERE
#a)
import numpy as np

revenues = np.array([120, 95, 200, 180, 160, 210, 190])

print(revenues)

[120  95 200 180 160 210 190]


In [27]:
#b)
print("ndim:", revenues.ndim)
print("shape:", revenues.shape)
print("size:", revenues.size)
print("dtype:", revenues.dtype)

ndim: 1
shape: (7,)
size: 7
dtype: int64


In [33]:
#c)
matrix = np.arange(1, 13).reshape(3,4)

print(matrix)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


### Exercise 4: Array Slicing

Using the `revenues` array:

a) Print the first three elements.

b) Print every other element starting from index 1.

c) Print the array in reversed order.

d) Using the 2D `data` array from Exercise 3c, extract and print:
- The first two rows and first two columns.
- The entire last column.

In [34]:
# YOUR CODE HERE
#a)
print(revenues[:3])

[120  95 200]


In [35]:
#b)
print(revenues[::-1])

[190 210 160 180 200  95 120]


In [41]:
#c)
print(matrix[:2,:2])
print(matrix[:,3])

[[1 2]
 [5 6]]
[ 4  8 12]


## Part 3: Pandas — Series and DataFrames

### Exercise 5: Creating a DataFrame

a) Create a DataFrame called `products` from the following dictionary:

```python
product_data = {
    "product": ["Laptop", "Phone", "Tablet", "Monitor"],
    "price": [1200, 800, 450, 350],
    "units_sold": [150, 300, 200, 100]
}
```

b) Print the DataFrame's `index` and `columns`.

c) Add a new column called `revenue` that is the product of `price` and `units_sold`.

d) Print the resulting DataFrame.

In [43]:
# YOUR CODE HERE
import pandas as pd

#a)
product_data = {
    "product": ["Laptop", "Phone", "Tablet", "Monitor"],
    "price": [1200, 800, 450, 350],
    "units_sold": [150, 300, 200, 100]
}

products = pd.DataFrame(product_data)

print(products)

   product  price  units_sold
0   Laptop   1200         150
1    Phone    800         300
2   Tablet    450         200
3  Monitor    350         100


In [49]:
#b)
index = products.index
columns = products.columns

print(index)
print(columns)

RangeIndex(start=0, stop=4, step=1)
Index(['product', 'price', 'units_sold'], dtype='object')


In [56]:
#c)
products["revenue"] = products["price"] * products["units_sold"]

print(products["revenue"])

0    180000
1    240000
2     90000
3     35000
Name: revenue, dtype: int64


In [57]:
#d)
print(products)

   product  price  units_sold  revenue
0   Laptop   1200         150   180000
1    Phone    800         300   240000
2   Tablet    450         200    90000
3  Monitor    350         100    35000


### Exercise 6: Creating DataFrames from Other Sources

a) Create a DataFrame from a list of dictionaries:

```python
employees = [
    {"name": "Anna", "department": "Finance", "salary": 4500},
    {"name": "Erik", "department": "Marketing", "salary": 4000},
    {"name": "Mia", "department": "Finance", "salary": 4800}
]
```

b) Create a DataFrame from a 2D NumPy array of shape `(3, 2)` with random values. Assign column names `"A"` and `"B"` and index labels `"x"`, `"y"`, `"z"`.

c) Print both DataFrames.

In [58]:
# YOUR CODE HERE
import pandas as pd

#a)
employee_data = [
    {"name": "Anna", "department": "Finance", "salary": 4500},
    {"name": "Erik", "department": "Marketing", "salary": 4000},
    {"name": "Mia", "department": "Finance", "salary": 4800}
]

employees = pd.DataFrame(employee_data)

print(employees)

   name department  salary
0  Anna    Finance    4500
1  Erik  Marketing    4000
2   Mia    Finance    4800


In [60]:
#b)
import numpy as np

data = np.random.rand(3,2)
matrix = pd.DataFrame(data, columns = ["A","B"], index = ["x", "y", "z"])

print(matrix)

          A         B
x  0.054421  0.111800
y  0.150700  0.401431
z  0.084765  0.557890


In [61]:
print(employees)
print()
print(matrix)

   name department  salary
0  Anna    Finance    4500
1  Erik  Marketing    4000
2   Mia    Finance    4800

          A         B
x  0.054421  0.111800
y  0.150700  0.401431
z  0.084765  0.557890


## Part 4: Pandas — Subsetting and Slicing

### Exercise 7: Selecting with `.loc`

Use the `products` DataFrame from Exercise 5 for this exercise.

a) Select and print the row at index `1` using `.loc`. What type is the result?

b) Select and print the row at index `1` using `.loc` with double brackets. What type is the result now?

c) Select and print only the `product` and `price` columns for all rows using `.loc`.

d) Select and print the `price` and `units_sold` columns for rows 1 to 2 (inclusive) using `.loc`.

In [63]:
# YOUR CODE HERE
#a)
print(products.loc[1])
print(type(products.loc[1]))

product        Phone
price            800
units_sold       300
revenue       240000
Name: 1, dtype: object
<class 'pandas.core.series.Series'>


In [64]:
#b)
print(products.loc[[1]])
print(type(products.loc[[1]]))

  product  price  units_sold  revenue
1   Phone    800         300   240000
<class 'pandas.core.frame.DataFrame'>


In [67]:
#c)
print(products.loc[:, ["product", "price"]])

   product  price
0   Laptop   1200
1    Phone    800
2   Tablet    450
3  Monitor    350


In [72]:
#d)
print(products.loc[1:2, ["price", "units_sold"]])

   price  units_sold
1    800         300
2    450         200


### Exercise 8: Selecting with `.iloc`

Using the same `products` DataFrame:

a) Select the first two rows using `.iloc`.

b) Select the element in the third row, second column using `.iloc`.

c) Select all rows but only the first and third columns using `.iloc`.

d) What is the difference between `df.loc[0:2]` and `df.iloc[0:2]`? Test both and explain in a comment.

In [77]:
# YOUR CODE HERE
#a)
print(products.iloc[0:2])

  product  price  units_sold  revenue
0  Laptop   1200         150   180000
1   Phone    800         300   240000


In [80]:
#b)
print(products.iloc[2, 1])

450


In [82]:
#c)
print(products.iloc[:, [0, 2]])

   product  units_sold
0   Laptop         150
1    Phone         300
2   Tablet         200
3  Monitor         100


In [85]:
#d)
print(products.loc[0:2])
print()
print(products.iloc[0:2])

  product  price  units_sold  revenue
0  Laptop   1200         150   180000
1   Phone    800         300   240000
2  Tablet    450         200    90000

  product  price  units_sold  revenue
0  Laptop   1200         150   180000
1   Phone    800         300   240000


### Exercise 9: Boolean Indexing

Using the `products` DataFrame:

a) Create a boolean mask that identifies products with a price above 500€. Print the mask.

b) Use the mask to subset the DataFrame and print only the expensive products.

c) In a single line, select all products where `units_sold` is greater than or equal to 200. Print the result.

In [ ]:
# YOUR CODE HERE


### Exercise 10: Putting It All Together

A small shop tracks weekly sales in a dictionary:

```python
sales_data = {
    "day": ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
    "customers": [30, 45, 50, 35, 60, 80, 70],
    "sales_eur": [600, 900, 1100, 750, 1300, 1800, 1500]
}
```

a) Create a DataFrame from this dictionary.

b) Add a column `avg_spend` that computes the average spending per customer (i.e., `sales_eur / customers`).

c) Using boolean indexing, filter the DataFrame to show only days where the number of customers exceeded 50.

d) Using `.iloc`, select the data for the weekend (last two rows) and all columns except `day`.

e) What was the total revenue for the week? Use NumPy or Pandas to compute and print the answer.

In [ ]:
# YOUR CODE HERE
